-- Minimum anti-multi-account defenses (⑨ Turnstile + ⑪ device guard) for
-- the participant-join path specifically. Not "1 person = 1 account" —
-- the goal is raising the cost of running several accounts from the same
-- browser above "just sign up with another email", not a hard guarantee.
--
-- Why this can't live entirely in SQL: join_game()'s existing shape is
-- called directly by the browser via supabase.rpc() — Postgres has no
-- visibility into HTTP cookies, so a device-identity check has to happen
-- in a Next.js route that can actually read/set an HttpOnly cookie, with
-- Postgres only able to enforce "was that check already done" after the
-- fact. So: join_game() keeps handling spectator role exactly as before
-- (unchanged, still directly callable by any client), but now refuses
-- role='participant' outright — participants must go through the new
-- join_game_participant() RPC below, which is service-role-only and only
-- ever called from app/api/join/participant/route.ts after that route has
-- verified a Turnstile token and the caller's own device cookie.
--
-- Run this manually in the Supabase SQL Editor (Database > SQL Editor).

begin;

-- ── round_key: a fresh id per round, so the device guard only ever
-- compares devices within the *same* round, not across DTB's whole
-- history. Regenerated by admin_reset_game() below. ────────────────────
alter table public.game_state
  add column if not exists round_key uuid not null default gen_random_uuid();

-- ── participant_verifications: "this uid passed a Turnstile check
-- recently." Written only by the service-role route after a real
-- Cloudflare siteverify success — never by a client directly. ──────────
create table if not exists public.participant_verifications (
  guest_id    uuid primary key references auth.users(id) on delete cascade,
  verified_at timestamptz not null
);
alter table public.participant_verifications enable row level security;
-- No policies for anon/authenticated: only service_role (bypasses RLS)
-- ever touches this table.

-- ── device_round_guard: (round_key, device_hash) → the first uid that
-- claimed it this round. device_hash is an HMAC of the dtb_device cookie
-- value, computed server-side — never the raw cookie. ──────────────────
create table if not exists public.device_round_guard (
  round_key   uuid not null,
  device_hash text not null,
  guest_id    uuid not null,
  created_at  timestamptz not null default now(),
  primary key (round_key, device_hash)
);
alter table public.device_round_guard enable row level security;
-- No policies for anon/authenticated here either.

-- ── join_game(): unchanged for spectator (same validation, same advisory
-- lock, same upsert shape as Phase 8's version); now refuses participant
-- outright instead of branching into the phase-transition logic. ────────
create or replace function public.join_game(p_role text, p_nickname text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid              uuid := auth.uid();
  v_nickname         text := trim(p_nickname);
  v_old_role         text;
  v_operator_nickname text;
begin
  if v_uid is null then
    raise exception 'authentication required';
  end if;

  if p_role = 'participant' then
    raise exception 'participant join must go through the verified join route';
  end if;

  if p_role not in ('participant', 'spectator') then
    raise exception 'invalid role: %', p_role;
  end if;

  if length(v_nickname) < 2 or length(v_nickname) > 20 then
    raise exception 'invalid nickname';
  end if;

  select operator_nickname into v_operator_nickname from game_state where id = 1;
  if v_nickname = v_operator_nickname then
    raise exception 'nickname reserved';
  end if;

  perform pg_advisory_xact_lock(hashtext(v_uid::text)::bigint);

  select role into v_old_role from participants where guest_id = v_uid;

  insert into participants (guest_id, nickname, role, last_seen)
  values (v_uid, v_nickname, p_role, now())
  on conflict (guest_id) do update
    set nickname  = excluded.nickname,
        role      = excluded.role,
        last_seen = now();

  if v_old_role is null or v_old_role <> p_role then
    insert into chat_messages (guest_id, nickname, message, kind)
    values (
      v_uid, 'system',
      v_nickname || '님이 관전자로 입장했습니다 👋',
      'system'
    );
  end if;
end;
$$;

-- ── join_game_participant(): the only way a role='participant' row can
-- now be created. Caller identity (p_uid) is supplied by the route, not
-- read from auth.uid() — this runs with the service-role's own Postgres
-- role, which has no JWT/auth.uid() context, since the route calls it
-- only after independently verifying the user's access token itself. ──
create or replace function public.join_game_participant(
  p_uid uuid,
  p_nickname text,
  p_device_hash text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nickname          text := trim(p_nickname);
  v_is_anon           boolean;
  v_old_role          text;
  v_operator_nickname text;
  v_round_key         uuid;
  v_existing_uid      uuid;
begin
  if p_uid is null then
    raise exception 'authentication required';
  end if;

  if length(v_nickname) < 2 or length(v_nickname) > 20 then
    raise exception 'invalid nickname';
  end if;

  -- Same rule join_game() has always enforced for participants: an
  -- Anonymous Auth session (app-wide identity bootstrap) can spectate but
  -- never hold a real participant slot.
  select is_anonymous into v_is_anon from auth.users where id = p_uid;
  if coalesce(v_is_anon, true) then
    raise exception 'participant role requires a signed-in account';
  end if;

  if p_device_hash is null or p_device_hash = '' then
    raise exception 'device check required';
  end if;

  -- Turnstile proof, recent enough to matter (10 min covers a slow /join
  -- flow without leaving a stale pass usable hours later).
  if not exists (
    select 1 from participant_verifications
    where guest_id = p_uid and verified_at > now() - interval '10 minutes'
  ) then
    raise exception 'verification required';
  end if;

  select operator_nickname into v_operator_nickname from game_state where id = 1;
  if v_nickname = v_operator_nickname then
    raise exception 'nickname reserved';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_uid::text)::bigint);

  select round_key into v_round_key from game_state where id = 1 for update;

  select guest_id into v_existing_uid
  from device_round_guard
  where round_key = v_round_key and device_hash = p_device_hash;

  if v_existing_uid is null then
    insert into device_round_guard (round_key, device_hash, guest_id)
    values (v_round_key, p_device_hash, p_uid);
  elsif v_existing_uid <> p_uid then
    raise exception 'this device already joined as a participant this round';
  end if;
  -- v_existing_uid = p_uid: same user retrying (e.g. network hiccup) — allowed through.

  select role into v_old_role from participants where guest_id = p_uid;

  insert into participants (guest_id, nickname, role, last_seen)
  values (p_uid, v_nickname, 'participant', now())
  on conflict (guest_id) do update
    set nickname  = excluded.nickname,
        role      = 'participant',
        last_seen = now();

  if v_old_role is null or v_old_role <> 'participant' then
    insert into chat_messages (guest_id, nickname, message, kind)
    values (
      p_uid, 'system',
      v_nickname || '님이 참여자로 입장했습니다 👋',
      'system'
    );
  end if;

  update game_state
  set phase = 'strategy', strategy_started_at = now()
  where id = 1 and phase = 'waiting';
end;
$$;

revoke all on function public.join_game_participant(uuid, text, text) from public, anon, authenticated;
grant execute on function public.join_game_participant(uuid, text, text) to service_role;

-- ── admin_reset_game(): also rolls the round key and clears the two
-- guard tables, so a fresh round doesn't inherit the previous round's
-- device/verification state. ────────────────────────────────────────────
create or replace function public.admin_reset_game()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from chat_messages where true;
  delete from participants where true;
  delete from device_round_guard where true;
  update game_state set
    phase = 'waiting',
    strategy_started_at = null,
    game_started_at = null,
    winner_id = null,
    winner_nickname = null,
    winner_price = null,
    winner_claimed_at = null,
    round_key = gen_random_uuid()
  where id = 1;
end;
$$;

commit;
